export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    GET_PHRASE: "GET_PHRASE",
    PHRASE_SUCCESS: "PHRASE_SUCCESS",
    GET_PRIVATE_PHRASE: "GET_PRIVATE_PHRASE",
    PHRASE_PRIVATE_SUCCESS: "PHRASE_PRIVATE_SUCCESS",
    FAILURE_PHRASE: "FAILURE_PHRASE",

    CREATE_REQUEST: "CREATE_REQUEST",
    CREATE_SUCCESS: "CREATE_SUCCESS"
};
