"use strict"
module.exports = {
    NOT_RESPECTED_RADAR: "NOT_RESPECTED_RADAR",
    AVG_SPEED: "AVG_SPEED",
    BRAKING_ABRUPT: "BRAKING_ABRUPT",
    KILOMETERS_TRAVELED: "KILOMETERS_TRAVELED",
    HIGH_ACELERATION: "HIGH_ACELERATION",
    DRIVING_TIME: "DRIVING_TIME",
    PHONE_DISTRACTION: "PHONE_DISTRACTION",
    NOT_RESPECTED_MAX_SPEED: "NOT_RESPECTED_MAX_SPEED",
    CRASH: "CRASH"
}
