"use strict"
module.exports = {
    KILOMETERS_TRAVELED: "KILOMETERS_TRAVELED",
    NOT_RESPECTED_MAX_SPEED: "NOT_RESPECTED_MAX_SPEED",
    DRIVING_TIME: "DRIVING_TIME",
    PHONE_DISTRACTION: "PHONE_DISTRACTION"
}
