service: dante-genosha-react
frameworkVersion: "=1.26.1"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  timeout: 20
  region: us-east-1
  environment:
    SECRET: ${file(./config.${self:provider.stage}.json):SECRET}
    
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
        - "ec2:CreateNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "s3:*"
        - "cloudformation:*"
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  login:
    warmup: production
    name: ${self:provider.stage}-login
    handler: services/LoginService.login
    events:
      - http:
          path: api/v1/login
          method: post
  getUser:
    name: ${self:provider.stage}-get-user
    handler: services/LoginService.getUser
    events:
      - http:
          path: api/v1/user
          method: get